poketwo/poketwo

cogs/shop.py, cogs/trading.py
=> Make coins pretty

cogs/config.py, cogs/shop.py, helpers/constants.py, helpers/mongo.py
- Add p!serverconfig
- Fixed prefix bug
- Reworked master boxes
=> Some fixes

cogs/config.py, cogs/help.py, helpers/pagination.py
Add option to see which commands to run in p!config with p!config help
=> Improve config.py

bot.py, cogs/admin.py, cogs/auctions.py, cogs/battling.py, cogs/bot.py, cogs/config.py, cogs/data.py, cogs/halloween.py, cogs/help.py, cogs/market.py, cogs/mongo.py, cogs/pokemon.py, cogs/shop.py, cogs/spawning.py, cogs/trading.py, helpers/pagination.py, launcher.py, migrations/2020-09-06-1_make_global_pokemon.py, migrations/2020-09-06-2_remove_local_pokemon.py, migrations/2020-09-06-3_update_listings.py, migrations/2020-09-09-backfill_moves.py, migrations/2020-09-17-create_timestamps.py, migrations/2020-10-04-1_make_indices.py, migrations/2020-10-04-2_add_indices.py, migrations/2020-10-04-3_add_next_idx.py, migrations/2020-10-04-4_add_selected_id.py, server.py
Removed unused imports and reorganised all other imports per PEP 8.
=> Optimised Imports

cogs/spawning.py
=> Trying to implement Issue #75

cogs/spawning.py
Unlocks channel once redeemspawn is caught.
=> Solution for #96

cogs/auctions.py
Do you want to lower starting bid to **8888 Pokécoins** on the **48.39% Greninja**? [y/N]
=> Enhancement: Auction lowerstart verification

cogs/market.py, cogs/pokemon.py, helpers/constants.py
Enables market listing search sort by id asc. and desc.
=> Enhancement: Market Sort by id

cogs/pokemon.py
Fixes bug reported by community post https://discord.com/channels/716390832034414685/719100151146348544/799060915261014036
Thank you for your report.
=> Fixes Pokedex Page Count

cogs/shop.py
I've seen a few people trying to use p!store and having it not work, not really a big deal but a minor QOL enhancement.
=> Added store aliases to shop command

cogs/auctions.py, cogs/market.py, cogs/pokemon.py, cogs/trading.py
**Added:** 
1. Rarity filters (mythical, legendary, ultrabeast) may now be appended.
Ex: `p!p --leg --myth --ub`
2. Filter --embedcolor (or --ec) to filter all Pokemon with custom embed color enabled.
Ex: `p!p --ec`
**Enhanced:**
1. Duplicate IV Flag argparse.
=> Enhancement: Filters

cogs/market.py, cogs/pokemon.py
**Enhanced:**
1. Market Listing
Added field with Listing ID and market Price.
2. Pokemon Un-mega
Added [y/N] verification with descriptions.
=> Enhancement: Market Listing Details, Unmega Verification

cogs/shop.py
Suggested fix for #176 with `find_one_and_update`
=> Fixes #176

cogs/spawning.py
I've been playing for a long time and I haven't caught a shiny, so this update will help fix this issue!
=> Increase shiny rates for keelay#3500 because I have been having a hard time catching shinies

bot.py, cogs/auctions.py, cogs/battling.py, cogs/bot.py, cogs/christmas.py, cogs/halloween.py, cogs/market.py, cogs/pokemon.py, cogs/quests.py, cogs/shop.py, cogs/spawning.py, cogs/trading.py, helpers/constants.py, helpers/pagination.py
made pink embeds defacto or whatever :keqlove:
=> pink embeds

cogs/spawning.py
The thingy request in issue #257 
E.g.
Congratulations Witherr🖤! You caught a level 1 Ralts!
Shiny streak reset. (**652**)
These colors seem unusual.. ✨
=> Shows the shiny streak when it is reset due to catching the shiny.

cogs/auctions.py, cogs/market.py
Would this work for the FR #261 ?
=> Embedcolor on market and auction infos

cogs/auctions.py, cogs/help.py, cogs/market.py, cogs/pokemon.py, cogs/trading.py, helpers/flags.py
This fixes the issue described in #267 , i have done primative testing in my own bots, however this should definitely be tested more/carefully reviewed just in case
=> fix issue with flag converter in 2.0

.github/workflows/docker-image.yml, .gitmodules
=> Update various evolutions

cogs/bot.py
=> Fix bug with flags in edited commands

cogs/christmas_2021.py
=> Fix variable naming

cogs/christmas_2021.py
This PR adds a varied embed color every time the p!event command is used[Christmas 2021]. I'd like to thank Witherr🖤#5417
on discord for helping on this PR.
=> Update christmas_2021.py 

cogs/bot.py
=> Add Suspension Appeal Link

cogs/battling.py, cogs/trading.py
This fixes the error caused while trying to trade/battle with suspended users
Thank you Connor and Septu for brining this up.
**Maintainers of this repository have permissions to edit this Pull Request.**
=> Fix error regarding suspended users

cogs/summer_2023.py
This PR has been tested!
- Make riddle name parsing the same as catching; base pokemon names are now supported for pokemon forms
- Add warning that expedition will cost Summer Tokens
- Add info about how to obtain Summer Tokens when you don't have enough
- Add info about how to obtain Fishing Baits when you don't have enough
- Fix riddle notification DMs not being sent
- POTENTIAL fix for delayed fishing bait updates; Was unable to reproduce so could not verify. Fixed the one thing that stuck out to me, but not sure if that's the cause of this bug.
=> Improvements and Bug Fixes for the Summer 2023 Event

cogs/battling.py
This PR implements the following changes:
- Fixed negative HP caused by ailments
- Fixed missing ailment damage indicator
- Fixed negative HP caused by recoil moves
- Fixed pokemon index incrementing in battle start embed
- Fixed Shadow type pokemon breaking battle
- Fixed 'Never misses' moves always missing
=> POK-172 Fix well known battling bugs

bot.py, cogs/admin.py, cogs/anniversary_2022.py, cogs/auctions.py, cogs/battling.py, cogs/bot.py, cogs/christmas_2022.py, cogs/config.py, cogs/lang.py, cogs/market.py, cogs/noevent.py, cogs/pokemon.py, cogs/quests.py, cogs/shop.py, cogs/spawning.py, cogs/trading.py, helpers/context.py, helpers/pagination.py, lang/en-US/admin.ftl, lang/en-US/auctions.ftl, lang/en-US/battling.ftl, lang/en-US/config.ftl, lang/en-US/errors.ftl, lang/en-US/main.ftl, lang/en-US/market.ftl, lang/en-US/pokemon.ftl, lang/en-US/quests.ftl, lang/en-US/shop.ftl, lang/en-US/spawning.ftl, lang/en-US/trading.ftl
Every command needs testing; a lot of basic functionality may be broken.
=> Localize all user-facing messages across the bot
