poketwo/poketwo

cogs/pokemon.py, cogs/shop.py, cogs/spawning.py, cogs/trading.py
This PR converts references of `discord.Member.name` to `discord.Member.display_name`, which means server-specific nicknames will be used in messages, rather than their underlying handle.
Current Behaviour:
New Behaviour:
=> Use a player's Discord Nickname, rather than their handle

cogs/spawning.py
In cogs/spawning.py:80ff the XP of the selected pokemon are increased only in the database but afterwards the check for possible levelup is performed with the old XP value before increasing. This leads to XP overflowing the max XP and the level up performed one message too late. Ideally the level up should happen in the moment the XP reaches or exceeds the max XP.
=> Levelupcheck is performed with the old XP value before gaining XP, allowing XP overflow

cogs/spawning.py
I added two minor improvements to reduce database accesses:
* When a pokémon is on level 100, the XP are only set to max_xp if they are below
* The guild will only be fetched when a spawn is actually triggered
=> reduce some database accesses while spawning

cogs/bot.py
Allow the `p!pick` command to use also non-English names.
=> allow picking starters with all available languages

cogs/spawning.py
Send congratulatory message with species name from dex_number rather than species name directly. This issue would only exist for catchable pokemons with dex_number different from id.
=> Suggested fix for Issue#78

cogs/auctions.py
Prevent users from circumventing Line 192 in auctions.py. (invalid bid increments)
**Before:** p!a start (id) (time) 888888 888888, then p!a lowerstart (id) 1 lowers start to 1 and keeps increment at 888888
**After:** p!a start (id) (time) 888888 888888, then p!a lowerstart (id) 1 raises "You may not set the new starting bid to a value less than your bid increment."
=> Auctions: Disable Lowering Start past Bid Increment

cogs/bot.py
Added a listener to reprocess commands after being edited, instead of having to retype or copy and paste the previous message. This makes it easier to correct small mistakes in Pokémon names with a simple edit.
=> Implemented message edit reprocess

cogs/auctions.py, cogs/market.py
Due to popular community and staff suggestion, disabled listing of **selected** and **favorited** Pokemon in market. 
This fix would:
1. Prevent accidental listing of favorited Pokemons
2. Disallow Pokemon being already favorited when it is bought from market
3. Fix the "You don't have a Pokemon selected" bug reproduced when the selected Pokemon is listed on market.
=> Fixes for market.py and auction.py

cogs/pokemon.py
**Main Changes:**
1. Split `p!favorite` function from toggling favorite state to the two separate functions below.
2. `p!favorite` to favorite, and `p!unfavorite` to remove favorite.
3. Added `p!favoriteall` and `p!unfavoriteall` for mass favoriting/unfavoriting Pokemon.
**Stylistic Changes:**
1. Added friendly reminder to guide players when using `p!favorite` and `p!favoriteall` on already favorited Pokemon.
2. Removed redundant code from lines 180-184.
2. Reordered command aliases from long to short.
=> Enhancements: Favoriting Pokemon

cogs/pokemon.py
Adds the ability to evolve multiple Pokémon at once using `commands.Greedy`.
The number of Pokémon is capped at 30, and anything less than 20 Pokémon will be represented as fields, while anything between 20 and 30 will be in the embed description. Thumbnail sprites will only be used when singular Pokémon are evolved.
Resolves #113
=> Add ability to evolve multiple Pokémon

cogs/mongo.py, cogs/pokemon.py
**Main Changes**
1. Display more information during `p!release`.
Added :sparkles:, IV.
Added "Can't find/release (x) Pokemon" message.
2. Require text confirmation (instead of y/n) during `p!release`.
Thank you Sk#4676 for the two suggestions above!
3. Display rarity for rare pokemons in dex.
Thank you Yiqii#6383 for the suggestion above!
**Stylistic Changes**
1. Display custom server prefixes in `p!favoriteall` support message.
Thank you corpsesimp#3949 for the suggestion above!
=> A Couple Display Enhancements

cogs/auctions.py, cogs/pokemon.py
**Enhanced:**
Auction Overbid DM Notification - Added `Current Bid: (x) Pokecoins.`
**Added:**
Spelling Support for word "favorite/favourite" in Un/Favoriteall confirmations.
=> Enhanced: Details in Bid and Un/Favoriteall

cogs/auctions.py, cogs/market.py, cogs/pokemon.py, cogs/trading.py, helpers/constants.py
**Changes**
1. Added Filters for Pokemon with IV Duplicates
**Filter Signature:**
`--<filter> <iv>`
Now, you may use `--triple`, `--quadruple`,`--quintuple`, and `--hextuple`, to filter your searches! Detailed examples given below.
2. Added Filter Nicknames
a. `--triple` may also be called by `--three`
b. `--quadruple` may also be called by `--four`
c. `--quintuple` may also be called by `--pentuple` and `--five`
d. `--hextuple` may also be called by `--six`
3. List of Commands Affected
a. `p!p`, `p!nickall`, `p!favoriteall`, `p!unfavoriteall`,`p!releaseall`
b. `p!auction search`
c. `p!market search`
d. `p!trade addall`
**Example**
1.  For example, you have 3 Pokemon in your inventory of the following IV's
Pokemon 1: IV's {15, 15, 13, 14, 15, 15}
Pokemon 2: IV's {15, 15, 13, 15, 20, 10} …
=> Added Match for Duplicate IV's

cogs/pokemon.py
Should be a temporary fix for #185  trade-selecting. Owner-checks for commands might be needed in the future.
=> Temp-fix for #185

cogs/pokemon.py
I'm not sure why `num = await self.bot.mongo.fetch_pokemon_count(ctx.author)` was needed. I think this is why p!select has been slow? Please correct me if I'm missing something here.
=> Fix p!select

cogs/spawning.py
Made it so it no longer shows the confirmation message if you try to p!sh the Pokemon you're already hunting, now instead shows "You are already hunting this pokémon with a streak of <current streak>".
(sorry if any of the code is faulty i didn't test it :sadge:)
=> Made it so you can't p!sh the Pokemon you're already hunting.

cogs/spawning.py
Resolves #122 
The enumeration used for `blanks` (for Tapu Lele) is `0123 4567`, but the enumeration used when generating the hint was `0123 0123`
The hint became empty when `blanks = [4, 5, 6, 7]`, and the hint may also completely give the answer when `blanks = [0, 1, 2, 3]`
This PR should fix the hint generation for species with more than one words
=> Fix blank hint

cogs/mongo.py, cogs/spawning.py
- Allow toggling on whether you will get pinged when catching a pokémon.
- To toggle: p!togglemention
- This command works in a similar way to p!togglebal
=> Catch Mentions

cogs/auctions.py
This pr replaces the` asyncio.Semaphore(1)`(which is actually the same as an asyncio.Lock) an defaultdict of asyncio.Locks, which will use the guild id as the key.
This is good once auctions is released to multiple guilds, since auctions from different guilds shouldn't conflict.
This pr also adds a lock to the ending auction process, which should fix issues with you losing money but not winning the auction.
=> fix issues with auctions ending before you finish bidding

cogs/auctions.py, cogs/battling.py, cogs/pokemon.py, cogs/shop.py, cogs/spawning.py
In some commands, the bot refers to `p!` as a prefix whereas the prefix for that particular guild or the prefix used by the user might not be `p!`.
For example, this:
I use `-` as a prefix but poketwo refers to `p!` as a prefix, even though `p!` is not a prefix in this guild.
This PR changes that, and poketwo will refer to whatever prefix the author is using as the prefix in its messages.
=> Changed all instances of `p!` to `{ctx.prefix}` to make the messages more dynamic

cogs/christmas_2021.py
This PR removes the button which directs users to [top.gg](https://top.gg/bot/716390085896962058/vote) , which isn't required in this case.
=> Remove the top.gg button from the Christmas Event's Embed

cogs/pokemon.py
Suggested in #108, this PR (hopefully) makes it possible to sort p!pokemon ascending/descending in the same way as the order filter for market search and auction search.
=> Make it possible to use +/- to order ascending/descending.

cogs/battling.py, cogs/pokemon.py, cogs/trading.py
- Adds the suspension check to a few commands which did not have it, allowing suspended users to use those commands (e.g. favorite)
- Prevents users from requesting battles/trades from suspended users
- Allows suspended users to cancel battles/trades (for cases where they msy have been suspended while in one
=> Add the suspension check to commands where it was missing

cogs/config.py
When typing `p!configuration` in a server with no icon, the command doesn't work since the below cannot fetch an icon.
```py
embed.set_thumbnail(url=ctx.guild.icon.url)
```
The fix is to add a check to see if the server has a icon.
```py
if ctx.guild.icon:
embed.set_thumbnail(url=ctx.guild.icon.url)
```
=> Fix config.py

cogs/anniversary_2022.py
A really simple spelling mistake which can be fixed by removing `!` next to `ctx.prefix`
=> Simple Spelling Error

bot.py
This fixes duplication of moves caused when the command is called at the same time
=> Fix the error with learning moves

cogs/trading.py
Limits the length of the value of users' items fields, to prevent the trade from breaking when adding pokemon with longer names (such as Spring Fever Cubchoo)
=> Bandaid fix for trades breaking due to 1024 character limit when adding pokemon with long names

cogs/auctions.py
Similar to buying from market, it should not be possible to bid while in a trade. This is potentially abusable.
=> Disallow bidding on auctions while in trade

cogs/lang.py, lang/en-US/cogs.ftl, lang/en-US/commands.ftl, lang/en-US/help.ftl, lang/en-US/main.ftl
Unfortunately, we can't do this:
```
-pokemon = Pokémon
.plural = Pokémon
```
We can't seem to refer to `{-pokemon.plural}` inside of messages. You can only match on them inside of selectors. I'm not sure if this is even necessary, or the right thing to do when it comes to localizations 🤔 We might only know the right thing to do once we get more strings.
=> Add all cog description/command help strings to Fluent

bot.py
This PR fixes the problem of users mistakenly pinging the bot's assigned role instead of the bot and thinking it's a bug for not working, by making that role a prefix.
This only works because the bot is being pinged and hence receiving the message content.
New PR opened to master branch instead of production
=> Allow the bot's assigned role to be used as prefix
